backend:
  name: git-gateway
  branch: main # Jouw hoofd-tak

media_folder: "images/uploads" # Waar je foto's veilig worden opgeslagen
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projecten"
    folder: "_data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      - {label: "Omschrijving NL", name: "desc_nl", widget: "text"}
      - {label: "Omschrijving EN", name: "desc_en", widget: "text"}
